version: '3.2'
services:
  envoy:
    image: envoyproxy/envoy:latest
    ports:
    - 8000:80
    - 8001:8001
    volumes:
    - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.route-prefix=/prometheus
    - --web.external-url=http://localhost:9090/prometheus