version: '3.2'
services:
  envoy:
    image: envoyproxy/envoy:${ENVOY_TAG}
    ports:
    - 8000:80
    - 8001:8001
    volumes:
    - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
    - hello
  nginx:
    image: nginx:${NGINX_TAG}
    ports:
    - 9000:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - hello
  hello:
    build:
      context: hello
    ports:
    - 1111:1111